// Automatically generated by flapigen
package com.example.docxgenerator.lib;
import androidx.annotation.NonNull;

public final class AndroidDocBuilder {

    public AndroidDocBuilder() {
        mNativeObj = init();
    }
    private static native long init();

    public final boolean addText(@NonNull String text) {
        boolean ret = do_addText(mNativeObj, text);

        return ret;
    }
    private static native boolean do_addText(long self, @NonNull String text);

    public final boolean addFormattedText(@NonNull String text, boolean bold, boolean italic, boolean _underline, long font_size, @NonNull String color) {
        boolean ret = do_addFormattedText(mNativeObj, text, bold, italic, _underline, font_size, color);

        return ret;
    }
    private static native boolean do_addFormattedText(long self, @NonNull String text, boolean bold, boolean italic, boolean _underline, long font_size, @NonNull String color);

    public final boolean addParagraphWithAlignment(@NonNull String text, @NonNull String alignment) {
        boolean ret = do_addParagraphWithAlignment(mNativeObj, text, alignment);

        return ret;
    }
    private static native boolean do_addParagraphWithAlignment(long self, @NonNull String text, @NonNull String alignment);

    public final boolean addBulletItem(@NonNull String text) {
        boolean ret = do_addBulletItem(mNativeObj, text);

        return ret;
    }
    private static native boolean do_addBulletItem(long self, @NonNull String text);

    public final boolean addNumberedItem(@NonNull String text) {
        boolean ret = do_addNumberedItem(mNativeObj, text);

        return ret;
    }
    private static native boolean do_addNumberedItem(long self, @NonNull String text);

    public final boolean addTable(long rows, long cols) {
        boolean ret = do_addTable(mNativeObj, rows, cols);

        return ret;
    }
    private static native boolean do_addTable(long self, long rows, long cols);

    public final boolean addImage(@NonNull String file, long width, long height) {
        boolean ret = do_addImage(mNativeObj, file, width, height);

        return ret;
    }
    private static native boolean do_addImage(long self, @NonNull String file, long width, long height);

    public final boolean generateDocx(@NonNull String file_name) {
        boolean ret = do_generateDocx(mNativeObj, file_name);

        return ret;
    }
    private static native boolean do_generateDocx(long self, @NonNull String file_name);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ AndroidDocBuilder(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}